# Generated by Django 3.1 on 2020-08-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True)),
                ('userPw', models.CharField(max_length=50)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_num', models.IntegerField(null=True)),
                ('time', models.CharField(max_length=50)),
                ('usage', models.CharField(max_length=100)),
                ('max_supply', models.CharField(max_length=100)),
                ('lagging_power', models.CharField(max_length=100)),
                ('leading_power', models.CharField(max_length=100)),
                ('carbdiox', models.CharField(max_length=100)),
                ('lagging_powerfactor', models.CharField(max_length=100)),
                ('leading_powerfactor', models.CharField(max_length=100)),
            ],
        ),
    ]
