# Generated by Django 3.1 on 2020-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0002_logininfo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='userId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
