# Generated by Django 3.1 on 2020-09-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0003_auto_20200908_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerdata',
            name='carbdiox',
        ),
        migrations.RemoveField(
            model_name='powerdata',
            name='lagging_power',
        ),
        migrations.RemoveField(
            model_name='powerdata',
            name='lagging_powerfactor',
        ),
        migrations.RemoveField(
            model_name='powerdata',
            name='leading_power',
        ),
        migrations.RemoveField(
            model_name='powerdata',
            name='leading_powerfactor',
        ),
        migrations.AddField(
            model_name='powerdata',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='powerdata',
            name='period',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
