# Generated by Django 3.1 on 2020-10-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0004_auto_20200916_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='taskId',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
